/**
 * Platform-wide permission definitions.
 * 
 * moduleKey maps permissions to the overarching module.
 */
export const DefaultPermissions = [
  { action: "EMPLOYEE_VIEW", moduleKey: "HR" },
  { action: "EMPLOYEE_CREATE", moduleKey: "HR" },
  { action: "EMPLOYEE_EDIT", moduleKey: "HR" },
  { action: "EMPLOYEE_DELETE", moduleKey: "HR" },

  { action: "ATTENDANCE_VIEW", moduleKey: "ATTENDANCE" },
  { action: "ATTENDANCE_MANAGE", moduleKey: "ATTENDANCE" },

  { action: "PAYROLL_VIEW", moduleKey: "PAYROLL" },
  { action: "PAYROLL_MANAGE", moduleKey: "PAYROLL" },

  { action: "CRM_VIEW", moduleKey: "CRM" },
  { action: "CRM_MANAGE", moduleKey: "CRM" },
  { action: "CUSTOMER_VIEW", moduleKey: "CRM" },
  { action: "CUSTOMER_CREATE", moduleKey: "CRM" },
  { action: "CUSTOMER_UPDATE", moduleKey: "CRM" },
  { action: "CUSTOMER_DELETE", moduleKey: "CRM" },
  { action: "CUSTOMER_EXPORT", moduleKey: "CRM" },

  { action: "LEAD_VIEW", moduleKey: "LEAD_MANAGEMENT" },
  { action: "LEAD_MANAGE", moduleKey: "LEAD_MANAGEMENT" },

  { action: "PROJECT_VIEW", moduleKey: "PROJECTS" },
  { action: "PROJECT_MANAGE", moduleKey: "PROJECTS" },

  { action: "FINANCE_VIEW", moduleKey: "ACCOUNTING" },
  { action: "FINANCE_MANAGE", moduleKey: "ACCOUNTING" },
  { action: "ACCOUNT_VIEW", moduleKey: "ACCOUNTING" },
  { action: "ACCOUNT_CREATE", moduleKey: "ACCOUNTING" },
  { action: "ACCOUNT_EDIT", moduleKey: "ACCOUNTING" },
  { action: "ACCOUNT_DELETE", moduleKey: "ACCOUNTING" },
  { action: "JOURNAL_VIEW", moduleKey: "ACCOUNTING" },
  { action: "JOURNAL_MANAGE", moduleKey: "ACCOUNTING" },
  { action: "FISCALYEAR_MANAGE", moduleKey: "ACCOUNTING" },
  { action: "JOURNALENTRY_VIEW", moduleKey: "ACCOUNTING" },
  { action: "JOURNALENTRY_CREATE", moduleKey: "ACCOUNTING" },
  { action: "JOURNALENTRY_EDIT", moduleKey: "ACCOUNTING" },
  { action: "JOURNALENTRY_POST", moduleKey: "ACCOUNTING" },
  { action: "JOURNALENTRY_VOID", moduleKey: "ACCOUNTING" },
  { action: "LEDGER_VIEW", moduleKey: "ACCOUNTING" },
  { action: "LEDGER_EXPORT", moduleKey: "ACCOUNTING" },
  { action: "LEDGER_AUDIT", moduleKey: "ACCOUNTING" },
  { action: "TRIALBALANCE_VIEW", moduleKey: "ACCOUNTING" },
  { action: "TRIALBALANCE_EXPORT", moduleKey: "ACCOUNTING" },
  { action: "PROFITLOSS_VIEW", moduleKey: "ACCOUNTING" },
  { action: "PROFITLOSS_EXPORT", moduleKey: "ACCOUNTING" },
  { action: "CASHFLOW_VIEW", moduleKey: "ACCOUNTING" },
  { action: "CASHFLOW_EXPORT", moduleKey: "ACCOUNTING" },
  { action: "BALANCESHEET_VIEW", moduleKey: "ACCOUNTING" },
  { action: "BALANCESHEET_EXPORT", moduleKey: "ACCOUNTING" },
  { action: "POSTING_EXECUTE", moduleKey: "ACCOUNTING" },
  { action: "POSTING_REVERSE", moduleKey: "ACCOUNTING" },
  { action: "POSTING_AUDIT", moduleKey: "ACCOUNTING" },
  { action: "INVENTORY_POST", moduleKey: "INVENTORY" },
  { action: "INVENTORY_POST_REVERSE", moduleKey: "INVENTORY" },
  { action: "PAYROLL_POST", moduleKey: "PAYROLL" },
  { action: "PAYROLL_POST_REVERSE", moduleKey: "PAYROLL" },
  { action: "WAREHOUSE_VIEW", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_MANAGE", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_TRANSFER", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_ADJUST", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_RECEIVE", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_ISSUE", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_RESERVE", moduleKey: "INVENTORY" },
  { action: "BIN_MANAGE", moduleKey: "INVENTORY" },
  { action: "STOCKMOVEMENT_VIEW", moduleKey: "INVENTORY" },
  { action: "STOCKMOVEMENT_CREATE", moduleKey: "INVENTORY" },
  { action: "STOCKMOVEMENT_REVERSE", moduleKey: "INVENTORY" },
  { action: "BATCH_VIEW", moduleKey: "INVENTORY" },
  { action: "BATCH_MANAGE", moduleKey: "INVENTORY" },
  { action: "BATCH_ADJUST", moduleKey: "INVENTORY" },
  { action: "BATCH_QUARANTINE", moduleKey: "INVENTORY" },
  { action: "SERIAL_VIEW", moduleKey: "INVENTORY" },
  { action: "SERIAL_MANAGE", moduleKey: "INVENTORY" },
  { action: "SERIAL_TRANSFER", moduleKey: "INVENTORY" },
  { action: "SERIAL_SCRAP", moduleKey: "INVENTORY" },
  { action: "BARCODE_VIEW", moduleKey: "INVENTORY" },
  { action: "BARCODE_GENERATE", moduleKey: "INVENTORY" },
  { action: "BARCODE_PRINT", moduleKey: "INVENTORY" },
  { action: "GOODSRECEIPT_VIEW", moduleKey: "INVENTORY" },
  { action: "GOODSRECEIPT_CREATE", moduleKey: "INVENTORY" },
  { action: "GOODSRECEIPT_COMPLETE", moduleKey: "INVENTORY" },
  { action: "GOODSRECEIPT_CANCEL", moduleKey: "INVENTORY" },
  { action: "PUTAWAY_VIEW", moduleKey: "INVENTORY" },
  { action: "PUTAWAY_ASSIGN", moduleKey: "INVENTORY" },
  { action: "PUTAWAY_EXECUTE", moduleKey: "INVENTORY" },
  { action: "PUTAWAY_CANCEL", moduleKey: "INVENTORY" },
  { action: "TRANSFER_VIEW", moduleKey: "INVENTORY" },
  { action: "TRANSFER_CREATE", moduleKey: "INVENTORY" },
  { action: "TRANSFER_APPROVE", moduleKey: "INVENTORY" },
  { action: "TRANSFER_SHIP", moduleKey: "INVENTORY" },
  { action: "TRANSFER_RECEIVE", moduleKey: "INVENTORY" },
  { action: "TRANSFER_CANCEL", moduleKey: "INVENTORY" },
  { action: "ADJUSTMENT_VIEW", moduleKey: "INVENTORY" },
  { action: "ADJUSTMENT_CREATE", moduleKey: "INVENTORY" },
  { action: "ADJUSTMENT_APPROVE", moduleKey: "INVENTORY" },
  { action: "ADJUSTMENT_POST", moduleKey: "INVENTORY" },
  { action: "ADJUSTMENT_CANCEL", moduleKey: "INVENTORY" },
  { action: "CYCLECOUNT_VIEW", moduleKey: "INVENTORY" },
  { action: "CYCLECOUNT_CREATE", moduleKey: "INVENTORY" },
  { action: "CYCLECOUNT_ASSIGN", moduleKey: "INVENTORY" },
  { action: "CYCLECOUNT_APPROVE", moduleKey: "INVENTORY" },
  { action: "CYCLECOUNT_POST", moduleKey: "INVENTORY" },
  { action: "VALUATION_VIEW", moduleKey: "INVENTORY" },
  { action: "VALUATION_REBUILD", moduleKey: "INVENTORY" },
  { action: "VALUATION_REPORT", moduleKey: "INVENTORY" },
  { action: "REORDERPOLICY_VIEW", moduleKey: "PROCUREMENT" },
  { action: "REORDERPOLICY_MANAGE", moduleKey: "PROCUREMENT" },
  { action: "PURCHASEREQUEST_VIEW", moduleKey: "PROCUREMENT" },
  { action: "PURCHASEREQUEST_CREATE", moduleKey: "PROCUREMENT" },
  { action: "PURCHASEREQUEST_APPROVE", moduleKey: "PROCUREMENT" },
  { action: "PURCHASEREQUEST_CONVERT", moduleKey: "PROCUREMENT" },
  { action: "WAREHOUSE_DASHBOARD_VIEW", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_ANALYTICS_VIEW", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_REPORT_EXPORT", moduleKey: "INVENTORY" },
  { action: "PICKING_VIEW", moduleKey: "INVENTORY" },
  { action: "PICKING_ASSIGN", moduleKey: "INVENTORY" },
  { action: "PICKING_EXECUTE", moduleKey: "INVENTORY" },
  { action: "PACKING_VIEW", moduleKey: "INVENTORY" },
  { action: "PACKING_EXECUTE", moduleKey: "INVENTORY" },

  { action: "COMPANY_SETTINGS", moduleKey: "CORE" },
  { action: "MODULE_MANAGE", moduleKey: "CORE" },
  { action: "ROLE_MANAGE", moduleKey: "CORE" },
  { action: "USER_MANAGE", moduleKey: "CORE" },

  { action: "WORKFLOW_VIEW", moduleKey: "WORKFLOW" },
  { action: "WORKFLOW_CREATE", moduleKey: "WORKFLOW" },
  { action: "WORKFLOW_UPDATE", moduleKey: "WORKFLOW" },
  { action: "WORKFLOW_DELETE", moduleKey: "WORKFLOW" },
  { action: "WORKFLOW_EXECUTE", moduleKey: "WORKFLOW" },

  { action: "APPROVAL_VIEW", moduleKey: "APPROVAL" },
  { action: "APPROVAL_CREATE", moduleKey: "APPROVAL" },
  { action: "APPROVAL_UPDATE", moduleKey: "APPROVAL" },
  { action: "APPROVAL_APPROVE", moduleKey: "APPROVAL" },
  { action: "APPROVAL_REJECT", moduleKey: "APPROVAL" },

  { action: "REPORT_VIEW", moduleKey: "REPORTING" },
  { action: "REPORT_CREATE", moduleKey: "REPORTING" },
  { action: "REPORT_UPDATE", moduleKey: "REPORTING" },
  { action: "REPORT_DELETE", moduleKey: "REPORTING" },
  { action: "REPORT_EXPORT", moduleKey: "REPORTING" },
  { action: "REPORT_EXPORT", moduleKey: "REPORTING" },
  { action: "REPORT_MANAGE", moduleKey: "REPORTING" },

  { action: "NOTIFICATION_VIEW", moduleKey: "NOTIFICATIONS" },
  { action: "NOTIFICATION_CREATE", moduleKey: "NOTIFICATIONS" },
  { action: "NOTIFICATION_UPDATE", moduleKey: "NOTIFICATIONS" },
  { action: "NOTIFICATION_UPDATE", moduleKey: "NOTIFICATIONS" },
  { action: "NOTIFICATION_MANAGE", moduleKey: "NOTIFICATIONS" },

  { action: "API_KEY_VIEW", moduleKey: "API_PLATFORM" },
  { action: "API_KEY_CREATE", moduleKey: "API_PLATFORM" },
  { action: "API_KEY_DELETE", moduleKey: "API_PLATFORM" },
  { action: "WEBHOOK_VIEW", moduleKey: "API_PLATFORM" },
  { action: "WEBHOOK_CREATE", moduleKey: "API_PLATFORM" },
  { action: "WEBHOOK_MANAGE", moduleKey: "API_PLATFORM" },

  { action: "BRANCH_VIEW", moduleKey: "BRANCH" },
  { action: "BRANCH_CREATE", moduleKey: "BRANCH" },
  { action: "BRANCH_UPDATE", moduleKey: "BRANCH" },
  { action: "BRANCH_DELETE", moduleKey: "BRANCH" },
  { action: "BRANCH_MANAGE_USERS", moduleKey: "BRANCH" },

  { action: "INVENTORY_VIEW", moduleKey: "INVENTORY" },
  { action: "INVENTORY_CREATE", moduleKey: "INVENTORY" },
  { action: "INVENTORY_UPDATE", moduleKey: "INVENTORY" },
  { action: "WAREHOUSE_MANAGE", moduleKey: "INVENTORY" },
  { action: "SUPPLIER_MANAGE", moduleKey: "INVENTORY" },
  { action: "PURCHASE_MANAGE", moduleKey: "INVENTORY" },

  { action: "ANALYTICS_VIEW", moduleKey: "ANALYTICS" },
  { action: "ANALYTICS_MANAGE", moduleKey: "ANALYTICS" },
  { action: "INSIGHT_VIEW", moduleKey: "ANALYTICS" },
  { action: "INSIGHT_MANAGE", moduleKey: "ANALYTICS" },
  { action: "FORECAST_VIEW", moduleKey: "ANALYTICS" },
];
